### ISSUE TITLE
Remove "Processing math: 100%" from PNG image for poster

### ISSUE THREAD

**Issue by ffliu** [odeleongt/postr#14]
When I added math equations (say,“ $\beta+\Sigma$ “)  in the Rmarkdown file and then generated the PNG image file for a poster (using "postr::render("poster.html")"), the phrase “Processing math: 100%” shows up in the lower left corner. Is there a method to remove “Processing math: 100%” from the poster PNG image file?

**Comment by weiyangtham** [comment]
Try using the `delay` argument in `postr::render()`. This is the number of seconds to wait before taking a screenshot of the html page. 

E.g. `postr::render("poster.html", delay = 10)`

**Comment by ffliu** [comment]
Thank you! It works!
